apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app.kubernetes.io/name: spring-boot-app
    app.kubernetes.io/instance: demo-app
    app.kubernetes.io/version: "17"
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-app
      app.kubernetes.io/instance: demo-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        app.kubernetes.io/name: spring-boot-app
        app.kubernetes.io/instance: demo-app
        app.kubernetes.io/version: "17"
        app.kubernetes.io/managed-by: argocd
      annotations:
        # Enable Promtail scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"
        # Add logging annotations
        logging.io/collect: "true"
        logging.io/format: "json"
    spec:
      containers:
      - name: spring-boot-app
        image: 192.168.56.103:8082/demo-spring-boot-app:17
        ports:
        - containerPort: 8888
          name: http
        env:
        # Configure structured logging
        - name: LOGGING_PATTERN_CONSOLE
          value: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss.SSS}","level":"%level","thread":"%thread","logger":"%logger{36}","message":"%msg","mdc":"%X"}%n'
        - name: LOGGING_LEVEL_ROOT
          value: "INFO"
        - name: LOGGING_LEVEL_COM_EXAMPLE
          value: "DEBUG"
        # Add pod info to logs
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/ready
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot-app
  ports:
  - port: 88
    targetPort: 8888
    nodePort: 30088
